name: Deploy Dagster University
on:
  push:
    branches:
      - main
    paths:
      - course/**
      - .github/workflows/build-dagster-university.yml
  pull_request:
    paths:
      - course/**
      - .github/workflows/build-dagster-university.yml
concurrency:
  # Cancel in-progress runs on same branch
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy to Vercel Previews on pull request
      - name: Prepare DBT project for deployment
        run: |
          python -m pip install pip --upgrade
          cd project-repo
          pip install . --upgrade --upgrade-strategy eager
          dagster-dbt project prepare-and-package --file dagster_and_dbt/project.py
        shell: bash